### ISSUE TITLE
text-link() mixin doesn't work

### ISSUE THREAD

**Issue by sammularczyk** [StudioThick/megatype#14]
Background position is calculated incorrectly and therefore the line doesn't show up.

**Comment by tbredin** [comment]
This feature has always been a bit problematic, I'm still not at all happy with the CSS output of the current implementation (a lot of `background-position`). 

I'm torn between removing this entirely, or going the distance to fix up something that I think is a pretty opinionated implementation to begin with...

**Comment by tbredin** [comment]
It's probably worthwhile having this as a feature but I think it's worth discussing what the ideal implementation should look like

**Comment by tbredin** [comment]
Fixed in `1.0.8`
e553dd580ce4c8895fa64c4837731d8a8568820b
