### ISSUE TITLE
Enormous performance issues when toolset__math.scss is included

### ISSUE THREAD

**Issue by RoccellaRocks** [StudioThick/megatype#18]
First time using MegaType.

I am using it together with **Gulp**: when I include MegaType in my SCSS file and I run sass via Gulp, **the amount of CPU and RAM used increases up to the limit!** And, unless I do not manually stop Gulp, the process keeps running.

I performed some "tests": I excluded one by one every component of MegaType.
When I do not include the "**toolset__math**" I do not have this performance issue (even considering that I am not using the function inside this file).

**Comment by tbredin** [comment]
Hi there. I'm not sure why that file would be eating up memory; especially considering we just uncovered that it's not even used in the project anymore! I've actually just removed it entirely and pushed that up ready for you now. 

Additionally I'm interested to know what system you're on, and which gulp sass plugin you're using?

**Comment by RoccellaRocks** [comment]
I'm on Mac OS X 10.11.4, using Node 5.10.1 with Gulp 3.9.1 and gulp-sass 2.2.0.

I'm not sure either. When I discovered what occupied so much RAM and CPU (everything was really slow and iStat Menu "warned" me), I was a bit shocked and uncertain.

I will update MegaType via Bower as soon as possible.  👍🏻
Thank you.
