### ISSUE TITLE
Demo Paragraph does not sit on the grid?

### ISSUE THREAD

**Issue by dmitriz** [StudioThick/megatype#19]
The paragraph starting with "Theosophists have guessed at the " in the Demo does not seem to sit on the baseline grid.

Am I missing something?

**Comment by tbredin** [comment]
Hi there, 
After reading this question I've run another set of browser tests and can't see the issue anywhere we're testing, can you provide some system and browser information? I'll see what I can do.

**Comment by dmitriz** [comment]
Here is the fragment showing how the next paragraph gets off the grid:

http://cl.ly/3s1l2o0a0g0R

On Chrome 49, Mac OSX 10.8.5

Tried on Firefox 43.0.1 but the grid disappears when trying to zoom the font down for some reason.

As the font zooms but the grid doesn't, it does not work for most zooms.
(However, the Chrome's misalignment of the following paragraph persists even when zooming 
the previous paragraph correctly.)

**Comment by tbredin** [comment]
Still not able to replicate exactly what you're seeing; in your screenshot that `p` is off by exactly half a baseline unit. 

I think we've managed to replicate something similar (but not exactly the same) by fiddling with chrome's font settings; can you try creating a new chrome profile with default settings and no extensions enabled and see if the problem persists?

**Comment by dmitriz** [comment]
I have Chrome settings picking Very large font that seems to make it.
Your text gets on line when changing to Medium font.
However, I find it uncomfortable so have to stay with Very large.

**Comment by tbredin** [comment]
I don't think we're going to prioritise a fix for this; it looks to be isolated to chrome with non-default font settings, in which case we recommend using browser zoom instead when developing with MegaType.

Note there is a remaining issue with the debug grid and _some_ zooms (#20), but other than a couple of problematic zoom levels it should be working well.
