### ISSUE TITLE
Max and min sizes

### ISSUE THREAD

**Issue by rollecode** [StudioThick/megatype#2]
Hello! Having tried about 10 sass packages for setting type, I love megatype so far! So simple and effective, especially the debugging. I was wondering about min and max font sizes, because it's not always preferred to have extremely large font sizes on television screens and tiny on mobile. `$min-font-size` has no effect, or I'm not understanding something. Any way to add `$max-font-size` after certain breakpoint?

**Comment by rollecode** [comment]
Sorry, I take this back. I'm using fully fluid grids (jeet) instead of those snappy ones, so I guess I have to improvise. I'd still like to hear your thoughts on this @StudioThick.

**Comment by tbredin** [comment]
Hi, glad to hear your feedback. If you're using a grid system I recommend matching your megatype configure to the breakpoints you're using in the grid system (if applicable). Adding a max font size is an interesting suggestion, might have a look over the weekend. 
I'll have a look to see if min size has any bugs

**Comment by rollecode** [comment]
Thanks for the answer! I'm not using a grid system per se, with [jeet's](http://jeet.gs/) sass helpers you can easily set grids to columns with an include. Currently using megatype's default breakpoints, because they were very close to my previous breakpoints.

I have another question, if you don't mind. Is there a list for cap heights for fonts or do you figure them out by testing? also, it seems not always text is aligned directly on debugging lines, but I guess that's not possible especially for freely fluid grids (without momentarily static 'snappy' width).

![Screenshot](https://dl.dropboxusercontent.com/u/18447700/Screen%20Shot%202016-03-18%20at%2012.44.44.png)

Close enough, I guess.
