### ISSUE TITLE
Setting the font-family is not explicit in documentation

### ISSUE THREAD

**Issue by lobaak** [StudioThick/megatype#21]
It took a little time to figure out that the `typeset()` mixin does not actually set `font-family`. It would be nice to include a note in the documentation.

Here's an example:

```
h2 {
    font-family: font-family-of($sans);
    @include typeset($sans, 40px, 46px, 2, 2);
}
```

**Comment by tbredin** [comment]
Fixed in `1.0.8`
3253df3b7331129dc1d6e464e9d3b7e756f69e00
