### ISSUE TITLE
Example config for http://megatype.studiothick.com/

### ISSUE THREAD

**Issue by nsbingham** [StudioThick/megatype#25]
I've looked around, but didn't see the config used on http://megatype.studiothick.com/ anywhere. I was wondering if it'd be possible to make that available. I've read through the docs and the bootstrap example, but could use another good example of implementation.

Thanks for megatype! I've been trying to solve similar issues for a while now and this is the best approach I've found.

**Comment by tbredin** [comment]
Hey there. The build on that link is deployed from the `gh-pages` branch of this project, you can find it here:  
https://github.com/StudioThick/megatype/tree/gh-pages

I believe the config you're looking for is here, mostly using megatype defaults, with a few overrides:  
https://github.com/StudioThick/megatype/blob/gh-pages/app/styles/base/_variables.scss

Other places of interest from the demo; 
- [`_defaults.scss`](https://github.com/StudioThick/megatype/blob/gh-pages/app/styles/base/_defaults.scss) contains all the type sizes specced out for the demo
- The [modules folder](https://github.com/StudioThick/megatype/tree/gh-pages/app/styles/modules) has the styling for the sidebar, toggle control, and a few other custom elements in the demo
- There's a [snippet of inline javascript](https://github.com/StudioThick/megatype/blob/gh-pages/app/templates/partials/debugging.html) to make the toggles work
