### ISSUE TITLE
Line-length for Optimal Readability

### ISSUE THREAD

**Issue by glennphilp** [StudioThick/megatype#30]
As I am a beginner with MegaType, Is there already a function/mixin that can calculate line-length, based on font-size and line-height . It might not be possible to dynamically calculate max-width based on font-family, font-size, and line-height. 

The optimal suggested character count is 45 to 75.
[Optimal Characters Per Line](http://mikeyanderson.com/optimal_characters_per_line)

I even wonder if this tool could be turned into a Sass function that would output a max-width based on the typeset mixin
[Golden Ratio Typography Calculator](http://www.pearsonified.com/typography/)

**Comment by glennphilp** [comment]
I think $type-measure setting is what I was looking for, although it would be nice to have a type-width function that could take characters-per-line ($cpl), font-size ($fs), and character-width ($cw) to output the max-width.

**Comment by tbredin** [comment]
In the interest of keeping megatype succint and focussed, I'm not sure a mixin is needed here and the $type-measure variable is probably going to be depreciated soon. 

I think this is best left as clearly exposed as possible since a simple `em` `max-width` is usually enough for this
