### ISSUE TITLE
Paragraphs inside list elements don’t line up properly

### ISSUE THREAD

**Issue by deepakjois** [StudioThick/megatype#32]
![screenshot 2016-08-23 21 19 34](https://cloud.githubusercontent.com/assets/5342/17899023/7ef3cd10-6977-11e6-96f6-222ce09cea47.png)

``` html
<ul>
  <li>
    <p>First paragraph.</p>
    <p>Continued.</p>
  </li>
  <li>
    <p>Second paragraph. With a code block, which must be indented eight spaces:</p>
  </li>
</ul>
```

**Comment by deepakjois** [comment]
Please feel free to close this issue (and #31 as well) if you believe this is not a bug. I posted this more with the intent to figure out if these kind of scenarios can be easily fixed with additional code outside the megatype framework.

**Comment by tbredin** [comment]
Hey @deepakjois unless we get a lot of interest I'm not sure if we'll end up supporting nested typeset elements; this would get very very complicated.

In cases like this to correct I suggest using a combination of manual top margins (not bottom margins as this will mess up the rhythm), and padding.
