### ISSUE TITLE
You may not @extend an outer selector from within @media.        You may only @extend selectors within the same directive.

### ISSUE THREAD

**Issue by kacakokeric** [StudioThick/megatype#36]
I have a problem! this is my package.json
{
  "name": "project",
  "version": "1.0.0",
  "description": "",
  "main": "gulpfile.js",
  "devDependencies": {
    "browser-sync": "^2.2.3",
    "del": "^1.1.1",
    "gulp": "^3.8.11",
    "gulp-autoprefixer": "^2.2.0",
    "gulp-concat-json": "^1.0.0",
    "gulp-data": "^1.2.0",
    "gulp-extend": "^0.2.0",
    "gulp-jsoncombine": "^1.0.2",
    "gulp-minify-css": "^0.5.1",
    "gulp-plumber": "^1.0.0",
    "gulp-print": "^1.1.0",
    "gulp-rename": "^1.2.0",
    "gulp-sass": "^3.0.0",
    "gulp-swig": "^0.7.4",
    "gulp-uglify": "^1.2.0",
    "node-bourbon": "^4.2.8",
    "node-neat": "^1.7.1-beta1",
    "path": "^0.11.14"
  },
this is ERROR!

essage:
Error: You may not @extend an outer selector from within @media.
       You may only @extend selectors within the same directive.
       From "@extend .layout-threefourths" on line 4 of src/assets/sass/_blockquote.scss
        on line 217 of src/assets/sass/_grid.scss
>>   .layout-threefourths,

Details:
    status: 1
    file: /Applications/MAMP/htdocs//template/src/assets/sass/_grid.scss
    line: 217
    column: 3
    formatted: Error: You may not @extend an outer selector from within @media.
       You may only @extend selectors within the same directive.
       From "@extend .layout-threefourths" on line 4 of src/assets/sass/_blockquote.scss
        on line 217 of src/assets/sass/_grid.scss
>>   .layout-threefourths,
   --^

    messageFormatted: src/assets/sass/_grid.scss
Error: You may not @extend an outer selector from within @media.
       You may only @extend selectors within the same directive.
       From "@extend .layout-threefourths" on line 4 of src/assets/sass/_blockquote.scss
        on line 217 of src/assets/sass/_grid.scss
>>   .layout-threefourths,
   --^

    messageOriginal: You may not @extend an outer selector from within @media.
You may only @extend selectors within the same directive.
From "@extend .layout-threefourths" on line 4 of src/assets/sass/_blockquote.scss

My files

.intro {
  .layout.container {
    @include media($tiny) {
      @extend .layout-full;
    }
    @include media($medium) {
      @extend .layout-semifull;
    }
    @include media($large) {
      @extend .layout-narrow;
    }
    .description, .inroduction {
      margin: 0;
    }
    .display-3 {
      margin-bottom: 32px;
      margin-top: 0;
      @include media($medium) {
        margin-top: 6px;
      }
    }
  }
}

help me to solve this problem
tnx

**Comment by kacakokeric** [comment]
someone has a solution

**Comment by tbredin** [comment]
Not an issue with megatype but misuse of extends. This is standard behaviour in sass, and is the result of using an extend within a media query (in megatype this is the `@include media` mixins).

To extend behaviour inside of media queries, I believe something along these lines should work, for example: 

```
@include media($tiny) {
    .class-to-extend {
        // rules
    }

    .some-other-class {
        @extend .class-to-extend;
    } 
}
```

ie; You can only extend classes that exist within the same media query directive
