### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by davelab6** [StudioThick/megatype#7]
I couldn't find the licensing information for this project easily; https://github.com/StudioThick/megatype/blob/master/bower.json#L8 says it is MIT. If so, please 
- [ ] include a  LICENSE.txt file with the MIT license,
- [ ] an AUTHORS.txt file with the copyright holders, and
- [ ] a CONTRIBUTORS.txt file with the human contributors if they don't own their copyrights. 

As an example, https://github.com/googlefonts/fontbakery/ is set up similarly to the above.

**Comment by tbredin** [comment]
Hey there. MIT is correct - we'll be looking at formalising this in the repo very soon; I think your example is a great reference for that, thanks.

**Comment by gvnn** [comment]
@tbredin I have added the licensing info, we might need to double check with @sawks
